name: Build and Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r book_catalog/requirements.txt
        pip install -r inventory_management/requirements.txt

    - name: Log in to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and push Docker images
      run: |
        docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}/book_catalog:latest ./book_catalog
        docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}/inventory_management:latest ./inventory_management
        echo ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }} | docker login ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }} -u ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }} --password-stdin
        docker push ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}/book_catalog:latest
        docker push ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}/inventory_management:latest

    - name: Set up Kubernetes CLI
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.18.0'

    - name: Get AKS credentials
      run: |
        az aks get-credentials --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AZURE_KUBERNETES_CLUSTER_NAME }}

    - name: Deploy to AKS
      run: |
        kubectl apply -f scripts/kubernetes/deployment.yaml
